@startuml base-classes

left to right direction

class Vertex {
    - _label : str
    - _weight : float
    + __init__(label: str, weight: float)
    + get_label() : str
    + get_weight() : float
    + set_label(new_name: str)
    + set_weight(new_weight: float)
}

note right of Vertex
  Vertex is used by both
  AdjacencyGraphList and
  AdjacencyMatrixGraph
end note

@enduml